language: python

sudo: false

python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'

install: pip install tox-travis

script: tox

deploy:
  provider: pypi
  user: radiantearth
  password:
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: radiantearth/radiantearth-python-client
    python: '3.6'
